name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-core-tests:
    name: Run core tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup venv & install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run pylint
        run: pylint src

      - name: Run flake8
        run: flake8 src

      - name: Run mypy
        run: mypy src

      - name: Run tests
        run: python -m pytest src/tests/tests.py