name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-core-tests:
    name: Run core tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup venv
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv venv
          source venv/bin/activate

      - name: Run pylint
        run: |
          pip install pylint
          python -m pylint src

      - name: Run flake8
        run: |
          pip install flake8
          python -m flake8 src

      - name: Run mypy
        run: |
          pip install mypy
          python -m mypy src

      - name: Run tests
        run: |
          pip install pytest
          python -m pytest src/tests/tests.py